spring.datasource.url=jdbc:mysql://localhost:3306/atmdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=San@112006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.thymeleaf.cache=false
server.port=8080
